# Word Replace Version 6.1
# Changing Word1 -> Word2 since 2011 (Not that long)

# Supported colors are: (case insensitive)
# - Black(&0)             Dark_Gray(&8)
# - Dark_Blue(&1)         Blue(&9)
# - Dark_Green(&2)        Green(&a)
# - Dark_Aqua(&3)         Aqua(&b)
# - Dark_Red(&4)          Red(&c)
# - Dark_Purple(&5)       Light_Purple(&d)
# - Gold(&6)              Yellow(&e)
# - Gray(&7)              White(&f)
# - You can also use Pink for Light_Purple and RAND for Random Colors
# This defaults to WHITE if it finds an error

# the replace-user-names node is if you want it so that when a user FULLY
# types in the name of another user, it is colored. Set to false to disable,
# set to true for random colors, or set to the color you want to activate.


# An Example is "AQUA,Admin,dcsiira:dc:siira"
# Which replaces the words "dc","dcsiira","siira","Admin" with "Admin", Colored in AQUA

replace-user-names: TRUE
normal-chat-color: WHITE
word-replace-list:
- AQUA,Admin,dcsiira:dc:siira
- RAND,Notch,Maker:xNotch
- DARK_BLUE,WAKAWAKA
