name: WordReplace
main: dcsiira.wordreplace.WordReplace
version: 5.1
commands:
  WR:
    description: States the version of the plugin or reloads the confiq
    usage: |
            /WR Help
  WReplace:
    description: States the version of the plugin or reloads the confiq
    usage: |
            /WReplace Help
  WordReplace:
    description: States the version of the plugin or reloads the confiq
    usage: |
            /WordReplace Help